name: haji_market
description: A new Flutter project.

publish_to: "none"

version: 4.3.8+1

environment:
  sdk: ^3.9.0

dependencies:
  anim_search_bar: ^2.0.2
  app_links: ^6.4.0
  auto_route: ^10.2.2
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  collection: ^1.19.1
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.2
  device_info_plus: ^11.3.3
  dio: ^5.9.0
  dotted_border: ^2.1.0
  easy_stepper: ^0.8.5+1
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_html: ^3.0.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.3
  fluttertoast: ^8.2.12
  freezed_annotation:
  gap: ^3.0.1
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  glowy_borders: ^1.0.2
  grouped_list: ^5.1.2
  http: ^1.1.0
  image_picker: ^1.2.1
  intercepted_client: ^0.0.1
  intl:
  json_annotation: ^4.9.0
  json_serializable: ^6.3.1
  mask_text_input_formatter: ^2.1.0
  meta: ^1.17.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.0.14
  permission_handler: ^11.4.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.5+1
  pull_to_refresh: ^2.0.0
  pure: ^0.3.0
  qr_flutter: ^4.1.0
  sentry_flutter: ^9.6.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  shimmer_animation: ^2.2.2
  show_image: 0.0.1
  sticky_grouped_list: ^3.1.0
  syncfusion_flutter_sliders: ^28.1.36
  talker: ^5.1.0
  talker_bloc_logger: ^5.1.0
  talker_dio_logger: ^5.1.0
  talker_logger: ^5.1.0
  timeago: ^3.7.0
  timeline_tile: ^2.0.0
  tuple: ^2.0.2
  url_launcher: ^6.3.2
  url_launcher_ios: ^6.3.2
  vector_graphics: ^1.1.19
  video_player: ^2.10.1
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.0.7
  yandex_mapkit: ^4.2.1

dev_dependencies:
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.3
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  lint: ^2.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Medium.otf
          weight: 500
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 100
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
