name: haji_market
description: A new Flutter project.

publish_to: "none"

version: 4.3.8+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.2.2
  bloc: ^9.1.0
  collection: ^1.19.1
  grouped_list: ^5.1.2
  timeline_tile: ^2.0.0
  flutter_svg: ^2.0.17
  freezed_annotation:
  mask_text_input_formatter: ^2.1.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  flutter_bloc: ^9.1.1
  flutter_rating_bar: ^4.0.1
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  get: ^4.6.5
  json_annotation: ^4.9.0
  json_serializable: ^6.3.1
  syncfusion_flutter_sliders: ^28.1.36
  get_storage: ^2.0.3
  flutter_masked_text2: ^0.9.1
  image_picker: ^0.8.6
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  video_player: ^2.7.0
  anim_search_bar: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  web_socket_channel: ^2.3.0
  show_image: 0.0.1
  sticky_grouped_list: ^3.1.0
  intl:
  pull_to_refresh: ^2.0.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.0.7
  geolocator: ^9.0.2
  flutter_html: ^3.0.0-alpha.3
  yandex_mapkit: ^4.2.1
  app_links: ^6.4.0
  share_plus: ^10.1.4
  path_provider: ^2.0.14
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  shimmer_animation: ^2.1.0+1
  shimmer: ^3.0.0
  qr_flutter: ^4.0.0
  htmltopdfwidgets: ^0.0.9+1
  dio: ^5.9.0
  cupertino_http: ^2.0.2
  cronet_http: ^1.3.2
  intercepted_client: ^0.0.1
  sentry_flutter: ^8.13.2
  talker: ^5.1.0
  talker_bloc_logger: ^5.1.0
  talker_dio_logger: ^5.1.0
  talker_logger: ^5.1.0
  timeago: ^3.7.0
  lottie: ^3.3.1
  vector_graphics: ^1.1.18
  shared_preferences: ^2.5.2
  device_info_plus: ^11.3.3
  tuple: ^2.0.2
  permission_handler: ^11.4.0
  gap: ^3.0.1
  fluttertoast: ^8.2.12
  pure: ^0.3.0
  modal_bottom_sheet: ^3.0.0
  easy_stepper: ^0.8.5+1
  glowy_borders: ^1.0.2
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0
  google_fonts: ^6.0.0
  package_info_plus: ^9.0.0


dev_dependencies:
  auto_route_generator: ^10.2.6
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  lint: ^2.6.1
  flutter_launcher_icons: ^0.14.4
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts: 
        - asset: fonts/Inter-Medium.otf
          weight: 500
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 100
  integrations:
    flutter_svg: true
    rive: true
    lottie: true