name: haji_market
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.8+80

environment:
  sdk: ">=2.19.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.4.0
  bloc: ^8.1.1
  grouped_list: ^5.1.2
  timeline_tile: ^2.0.0
  flutter_svg: ^1.1.3
  freezed_annotation:
  mask_text_input_formatter: ^2.1.0
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.2
  flutter_rating_bar: ^4.0.1
  http: ^0.13.5
  get: ^4.6.5
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  syncfusion_flutter_sliders: ^20.2.49
  get_storage: ^2.0.3
  flutter_masked_text2: ^0.9.1
  cached_network_image: ^3.1.0
  image_picker: ^0.8.6
  url_launcher: ^6.1.9
  video_player: ^2.7.0
  # cached_video_player: ^2.0.4
  anim_search_bar: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  web_socket_channel: ^2.3.0
  show_image: 0.0.1
  sticky_grouped_list: ^3.1.0
  intl: ^0.18.1
  pull_to_refresh: ^2.0.0
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.0.7
  geolocator: ^9.0.2
  flutter_html: ^3.0.0-alpha.3
  yandex_mapkit: ^3.2.0
  cupertino_icons: ^1.0.2
  uni_links: ^0.5.1
  screenshot: ^2.1.0
  share_plus: ^6.3.2
  path_provider: ^2.0.14
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  shimmer_animation: ^2.1.0+1
  shimmer: ^3.0.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.12.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/temp/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Italic-VariableFont_wght.ttf
        - asset: fonts/Nunito-VariableFont_wght.ttf
          style: italic

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/luna_market_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/luna_market_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/luna_market_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/luna_market_logo.png"
    # - assets/translations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
